# Generated by Django 5.0.1 on 2024-05-23 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendapp", "0002_company_answer_company_question_company_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="accessible_by",
            field=models.ManyToManyField(
                related_name="accessible_templates",
                to=django.conf.settings.AUTH_USER_MODEL,
            ),
        ),
    ]
